# Generated by Django 4.0.1 on 2022-01-21 04:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QnA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='question/questionImage'),
        ),
        migrations.AlterField(
            model_name='question',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='question/questionVideo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
