# Generated by Django 4.0.1 on 2022-01-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QnA', '0002_alter_question_img_alter_question_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
